### PR TITLE
include pacta.interactive.plot

### PR DESCRIPTION
**Pull request by cjyetman**

### CODE REVIEW

**Review by jdhoffa — CHANGES_REQUESTED** [review]
I believe you need to also add it to:
- `README.Rmd`
- then call `devtools::build_readme()`
- add a dummy import to `R/pactaverse.R` (to make sure R CMD Check doesn't complain about depending on a package but not using anything)

Then that should be good

**Comment by cjyetman** [comment]
side note: this is one of the reasons I don't like the README.Rmd thing... what could be a super simple PR that could be done easily through the GitHub webGUI becomes basically impossible

**Comment by cjyetman** [comment]
@jdhoffa can you take over here? I don't really understand these "dummy imports"

**Comment by jdhoffa** [comment]
> side note: this is one of the reasons I don't like the README.Rmd thing... what could be a super simple PR that could be done easily through the GitHub webGUI becomes basically impossible

https://github.com/RMI-PACTA/pactaverse/pull/9 should make it easy to make PRs from GitHub webGUI

**Comment by jdhoffa** [comment]
> @jdhoffa can you take over here? I don't really understand these "dummy imports"

Done. It just calls a random function from the package to prove to R CMD Check that it "depends on that package".

**Comment by jdhoffa** [comment]
> @jdhoffa can you take over here? I don't really understand these "dummy imports"

Ah I see. You did it mostly right, but used `pacta.interactive.report` (which is private still) instead of `pacta.interactive.plot`

**Comment by cjyetman** [comment]
> > @jdhoffa can you take over here? I don't really understand these "dummy imports"
> 
> Done. It just calls a random function from the package to prove to R CMD Check that it "depends on that package".

hmmmm, ok.... that didn't work with `pacta.interactive.report::trajectory_alignment_chart` for some reason

**Comment by jdhoffa** [comment]
> > > @jdhoffa can you take over here? I don't really understand these "dummy imports"
> > 
> > 
> > Done. It just calls a random function from the package to prove to R CMD Check that it "depends on that package".
> 
> hmmmm, ok.... that didn't work with `pacta.interactive.report::trajectory_alignment_chart` for some reason

Because you called `pacta.interactive.report` (which is private/ not yet a dependency of `pactaverse`) rather than `pacta.interactive.plot` :-S

**Pull request merged**
